const API_BASE_URL='https://attendance-management-v739.onrender.com/api';
const $=id=>document.getElementById(id);
const pages={login:$('login-page'),register:$('register-page'),forgot:$('forgot-page'),app:$('app-page')};
let loginRole='student',registerRole='student',currentView='dashboard',lecturerCourses=[];
function showPage(n){Object.values(pages).forEach(x=>x.classList.add('hidden'));pages[n].classList.remove('hidden')}
// Generic alert helper: every alert (app message, login/register/forgot errors) is shown
// once and auto-dismissed, and each message element keeps its own timer so an old message
// from a different role's screen never lingers into another role's view.
const MESSAGE_TIMERS={};
function flashMessage(elId,t,type='info',duration=4000){
  const e=$(elId);if(!e)return;
  if(MESSAGE_TIMERS[elId]){clearTimeout(MESSAGE_TIMERS[elId]);MESSAGE_TIMERS[elId]=null}
  e.textContent=t;e.className=`message ${type}`;
  if(!t){e.classList.add('hidden');return}
  MESSAGE_TIMERS[elId]=setTimeout(()=>{e.textContent='';e.className='message hidden'},duration)
}
function clearMessage(elId){flashMessage(elId,'')}
function msg(t,type='info'){flashMessage('app-message',t,type)}
function headers(){return {'Content-Type':'application/json',Authorization:`Bearer ${localStorage.getItem('campustrack_token')||''}`}}
async function api(path,opt={})
{const r=await fetch(API_BASE_URL+path,{...opt,headers:{...headers(),...(opt.headers||{})}});
let d={};try{d=await r.json()}catch{}if(r.status===401){logout();
    throw Error('Session expired. Please log in again.')}
    if(!r.ok||d.success===false)throw Error(d.message||'Request failed.');return d}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function user(){return JSON.parse(localStorage.getItem('campustrack_user')||'{}')}
function role(){return user().role}
function setTabs(sel,attr,val){document.querySelectorAll(sel).forEach(b=>b.classList.toggle('active',b.getAttribute(attr)===val))}
// Each role logs in with a different identifier: students use their registration number,
// lecturers and admins use their email. Switching tabs updates the field and clears any
// alert left over from a previous tab so one role's message is never shown on another's.
const LOGIN_IDENTITY={student:{label:'Registration number',placeholder:'2025/DSWE/DAY/1234/P'},lecturer:{label:'Email',placeholder:'lecturer@uiict.ac.ug'},admin:{label:'Email',placeholder:'admin@uiict.ac.ug'}};
function applyLoginIdentity(){const cfg=LOGIN_IDENTITY[loginRole];$('login-identifier-label').textContent=cfg.label;$('login-identifier').placeholder=cfg.placeholder;$('login-identifier').type=loginRole==='student'?'text':'email'}
document.querySelectorAll('.tab[data-role]').forEach(b=>b.onclick=()=>{loginRole=b.dataset.role;setTabs('.tab[data-role]','data-role',loginRole);applyLoginIdentity();clearMessage('login-error');$('login-form').reset()});
applyLoginIdentity();
document.querySelectorAll('.tab[data-reg-role]').forEach(b=>b.onclick=()=>{registerRole=b.dataset.regRole;setTabs('.tab[data-reg-role]','data-reg-role',registerRole);$('identity-label').textContent=registerRole==='student'?'Registration number':'Lecturer ID / Staff number';$('register-identity').placeholder=registerRole==='student'?'2025/DSWE/DAY/1590/G':'STAFF-001';clearMessage('register-message')});
$('register-link').onclick=e=>{e.preventDefault();clearMessage('login-error');showPage('register')};$('back-login').onclick=e=>{e.preventDefault();clearMessage('register-message');showPage('login')};$('forgot-link').onclick=e=>{e.preventDefault();clearMessage('login-error');showPage('forgot')};$('forgot-back').onclick=e=>{e.preventDefault();clearMessage('forgot-message');showPage('login')};
$('login-form').onsubmit=async e=>{e.preventDefault();clearMessage('login-error');const btn=$('login-btn');btn.disabled=true;try{const r=await fetch(API_BASE_URL+'/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({role:loginRole,emailOrUsername:$('login-identifier').value.trim(),password:$('login-password').value})});const d=await r.json();if(!r.ok||!d.success)throw Error(d.message||'Login failed.');localStorage.setItem('campustrack_token',d.data.token);localStorage.setItem('campustrack_user',JSON.stringify(d.data.user));$('login-form').reset();await openApp()}catch(e){flashMessage('login-error',e.message,'error')}finally{btn.disabled=false}};
$('register-form').onsubmit=async e=>{e.preventDefault();try{const identity=$('register-identity').value.trim();const body={role:registerRole,fullName:$('register-name').value.trim(),email:$('register-email').value.trim(),password:$('register-password').value};if(registerRole==='student')body.registrationNumber=identity;else body.lecturerId=identity;const r=await fetch(API_BASE_URL+'/auth/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok||!d.success)throw Error(d.message||'Registration failed.');flashMessage('register-message','Registration successful. You can now log in.','success');$('register-form').reset();setTimeout(()=>showPage('login'),800)}catch(e){flashMessage('register-message',e.message,'error')}};
$('forgot-form').onsubmit=async e=>{e.preventDefault();try{const r=await fetch(API_BASE_URL+'/auth/forgot-password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({emailOrUsername:$('forgot-identifier').value.trim()})});const d=await r.json();if(!r.ok||!d.success)throw Error(d.message);flashMessage('forgot-message',d.message,'info');if(d.data?.devToken){$('dev-token-box').textContent='Development reset token: '+d.data.devToken;$('dev-token-box').className='dev-token'}}catch(e){flashMessage('forgot-message',e.message,'error')}};
$('reset-form').onsubmit=async e=>{e.preventDefault();try{const r=await fetch(API_BASE_URL+'/auth/reset-password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:$('reset-token').value.trim(),newPassword:$('reset-password').value})});const d=await r.json();if(!r.ok||!d.success)throw Error(d.message);flashMessage('forgot-message',d.message,'success')}catch(e){flashMessage('forgot-message',e.message,'error')}};

document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>showView(b.dataset.view));
function showView(v){currentView=v;clearMessage('app-message');document.querySelectorAll('.view').forEach(x=>x.classList.add('hidden'));$(`view-${v}`).classList.remove('hidden');document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===v));const loads={dashboard:loadDashboard,'student-programs':loadStudentPrograms,'student-courses':loadStudentCourses,'student-lectures':loadStudentLectures,'student-attendance':loadStudentAttendance,'student-profile':()=>renderProfile('student-profile-card'),'lecturer-courses':loadLecturerCourses,'take-attendance':prepareTakeAttendance,'attendance-history':loadHistory,reports:loadReports,'lecturer-profile':()=>renderProfile('lecturer-profile-card'),'admin-programs':loadAdminPrograms,'admin-users':loadAdminUsers,'admin-student-attendance':loadAdminStudentAttendance,'admin-lecturer-attendance':loadAdminLecturerAttendance};if(loads[v])loads[v]().catch(e=>msg(e.message,'error'))}
function firstName(fullName){return String(fullName||'').trim().split(/\s+/)[0]||'there'}
async function openApp(){showPage('app');const u=user();$('role-label').textContent=u.role==='admin'?'Administrator':u.role==='lecturer'?'Lecturer':'Student';$('welcome-banner').textContent=`Welcome, ${firstName(u.fullName)}`;$('welcome-banner').classList.remove('hidden');$('student-nav').classList.toggle('hidden',u.role!=='student');$('lecturer-nav').classList.toggle('hidden',u.role!=='lecturer');$('admin-nav').classList.toggle('hidden',u.role!=='admin');showView('dashboard')}
async function loadDashboard(){const r=role();$('dashboard-subtitle').textContent=`Welcome, ${firstName(user().fullName)}`;if(r==='admin'){const d=(await api('/admin/dashboard')).data;$('dashboard-cards').innerHTML=`<div class="stat"><small>Programs</small><strong>${d.programs}</strong></div><div class="stat"><small>Students</small><strong>${d.students}</strong></div><div class="stat"><small>Lecturers</small><strong>${d.lecturers}</strong></div><div class="stat"><small>Course Units</small><strong>${d.courses}</strong></div><div class="stat"><small>Student Attendance</small><strong>${d.overallStudentAttendance}%</strong></div>`;$('dashboard-extra').innerHTML='<h3>Administrator Dashboard</h3><p class="muted">Add or delete programs, add course units inside them, monitor users, manage student attendance and record lecturer attendance.</p>'}else if(r==='lecturer'){const d=(await api('/lecturer/dashboard')).data;$('dashboard-cards').innerHTML=`<div class="stat"><small>Assigned Courses</small><strong>${d.assignedCourses}</strong></div><div class="stat"><small>Students</small><strong>${d.students}</strong></div><div class="stat"><small>Today's Attendance</small><strong>${d.todayAttendance}</strong></div><div class="stat"><small>Overall Attendance</small><strong>${d.overallAttendancePercentage}%</strong></div>`;$('dashboard-extra').innerHTML='<h3>Lecturer Dashboard</h3><p class="muted">Choose your course units, post lessons and monitor student attendance.</p>'}else{const [s,c]=await Promise.all([api('/attendance/my-statistics'),api('/courses/my')]);const x=s.data.overall;$('dashboard-cards').innerHTML=`<div class="stat"><small>Enrolled Courses</small><strong>${c.data.length}</strong></div><div class="stat"><small>Present</small><strong>${x.present}</strong></div><div class="stat"><small>Late</small><strong>${x.late}</strong></div><div class="stat"><small>Attendance</small><strong>${x.attendancePercentage}%</strong></div>`;$('dashboard-extra').innerHTML='<h3>Student Dashboard</h3><p class="muted">Enroll in a program to get every course unit under it, attend lessons your lecturers post, view attendance statistics and reset your password.</p>'}}
async function loadStudentPrograms(){const [av,mine]=await Promise.all([api('/programs/available'),api('/programs/my')]);const enrolledIds=new Set(mine.data.map(p=>p.id));$('available-programs-list').innerHTML=av.data.length?av.data.map(p=>`<div class="course-card"><h3>${esc(p.code)} — ${esc(p.name)}</h3><p class="muted">${(p.courses||[]).length} course unit(s) under this program.</p><button class="btn ${enrolledIds.has(p.id)?'outline':'primary'}" ${enrolledIds.has(p.id)?'disabled':''} onclick="enrollProgram(${p.id})">${enrolledIds.has(p.id)?'Enrolled':'Enroll'}</button></div>`).join(''):'<div class="card empty">No active programs are available.</div>';$('my-programs-list').innerHTML=mine.data.length?mine.data.map(p=>`<div class="course-card"><h3>${esc(p.code)} — ${esc(p.name)}</h3><p class="muted">Course units: ${(p.courses||[]).map(c=>esc(c.code)).join(', ')||'None yet'}</p></div>`).join(''):'<div class="card empty">You are not enrolled in any program yet.</div>'}
window.enrollProgram=async id=>{try{const d=await api('/programs/enroll/'+id,{method:'POST'});msg(d.message,'success');loadStudentPrograms()}catch(e){msg(e.message,'error')}};
async function loadStudentCourses(){const mine=await api('/courses/my');$('student-courses-list').innerHTML=mine.data.length?mine.data.map(c=>`<div class="course-card"><h3>${esc(c.code)} — ${esc(c.name)}</h3><p class="muted">Program: ${esc(c.program?.name||'—')}</p><p class="muted">Lecturer: ${esc(c.lecturer?.fullName||'Not assigned')}</p></div>`).join(''):'<div class="card empty">You are not enrolled in any course units yet. Enroll in a program first.</div>'}
async function loadStudentLectures(){const d=await api('/attendance/my-lectures');$('student-lectures-list').innerHTML=d.data.length?d.data.map(l=>`<div class="course-card"><h3>${esc(l.course.code)} — ${esc(l.course.name)}</h3><p><b>Every ${esc(l.dayOfWeek)}</b> · ${esc(l.startTime)} - ${esc(l.endTime)}</p><p class="muted">Lecturer: ${esc(l.course.lecturer||'Not assigned')}</p><label for="lecture-pin-${l.id}" class="muted">Current 4-digit lecturer PIN</label><input id="lecture-pin-${l.id}" inputmode="numeric" pattern="[0-9]{4}" maxlength="4" placeholder="0000" aria-label="4-digit lecturer PIN"><button class="btn primary" onclick="markLecture(${l.id})">Enter PIN & Register Attendance</button></div>`).join(''):'<div class="card empty">No scheduled lectures are available.</div>'}
window.markLecture=async id=>{const pin=$(`lecture-pin-${id}`).value.trim();if(!/^\d{4}$/.test(pin))return msg('Enter the current 4-digit PIN from your lecturer.','error');try{const d=await api('/attendance/mark',{method:'POST',body:JSON.stringify({lectureId:id,pin})});msg(d.message,'success');loadStudentLectures();loadStudentAttendance()}catch(e){msg(e.message,'error')}};
async function loadStudentAttendance(){const [r,s]=await Promise.all([api('/attendance/my-records'),api('/attendance/my-statistics')]);const x=s.data.overall;$('student-statistics').innerHTML=`<div class="stat"><small>Present</small><strong>${x.present}</strong></div><div class="stat"><small>Absent</small><strong>${x.absent}</strong></div><div class="stat"><small>Late</small><strong>${x.late}</strong></div><div class="stat"><small>Attendance</small><strong>${x.attendancePercentage}%</strong></div>`;$('student-attendance-body').innerHTML=r.data.length?r.data.map(a=>`<tr><td>${esc(a.date)}</td><td>${esc(a.course?.code||'Legacy')}</td><td>${esc(a.lecture?`${a.lecture.startTime}-${a.lecture.endTime}`:'')}</td><td class="status ${a.status}">${a.status}</td></tr>`).join(''):'<tr><td colspan="4">No attendance records.</td></tr>'}
async function loadLecturerCourses(){const d=await api('/courses/lecturer');lecturerCourses=d.data;$('lecturer-courses-list').innerHTML=lecturerCourses.length?lecturerCourses.map(c=>`<div class="course-card"><h3>${esc(c.code)} — ${esc(c.name)}</h3><p class="muted">Program: ${esc(c.program?.name||'—')}</p><div class="actions"><button class="btn primary" onclick="viewCourseStudents(${c.id})">View Students</button><button class="btn secondary" onclick="openCourseAttendance(${c.id})">Show Live PIN</button><button class="btn outline" onclick="openCourseAttendance(${c.id})">Monitor Attendance</button></div><div id="students-${c.id}"></div><div class="controls" style="margin-top:10px"><label class="muted" style="grid-column:1/-1">Post a Lesson</label><select id="lesson-day-${c.id}">${DAYS_OF_WEEK.map(day=>`<option value="${day}">${day}</option>`).join('')}</select><input id="lesson-start-${c.id}" type="time" title="Start time"><input id="lesson-end-${c.id}" type="time" title="End time"><button class="btn secondary" onclick="postLesson(${c.id})">Post Lesson</button></div><div id="lessons-${c.id}" class="muted"></div></div>`).join(''):'<div class="card empty">You have not chosen a course unit yet.</div>';lecturerCourses.forEach(c=>loadLecturerLessons(c.id));await loadLecturerAvailable()}
async function loadLecturerLessons(id){try{const d=await api(`/lecturer/courses/${id}/lectures`);$(`lessons-${id}`).innerHTML=d.data.length?'<p><b>Posted lessons:</b></p>'+d.data.map(l=>`<div style="margin:8px 0">Every ${esc(l.dayOfWeek)} · ${esc(l.startTime)}-${esc(l.endTime)} <button class="btn secondary" style="padding:2px 8px" onclick="showLessonPin(${l.id})">Show Live PIN</button> <button class="btn outline" style="padding:2px 8px" onclick="deleteLesson(${l.id},${id})">Remove</button><div id="lecture-pin-display-${l.id}" class="hidden"></div></div>`).join(''):'<p>No lessons posted yet.</p>'}catch(e){}}
window.showLessonPin=async lectureId=>{const el=$(`lecture-pin-display-${lectureId}`);if(el){el.className='message info';el.textContent='Generating current PIN…'}await loadLecturePin(lectureId)};
window.postLesson=async id=>{const dayOfWeek=$(`lesson-day-${id}`).value,startTime=$(`lesson-start-${id}`).value,endTime=$(`lesson-end-${id}`).value;if(!dayOfWeek||!startTime||!endTime)return msg('Choose the day of the week, start time and end time.','error');try{const d=await api(`/lecturer/courses/${id}/lectures`,{method:'POST',body:JSON.stringify({dayOfWeek,startTime,endTime})});msg(d.message,'success');loadLecturerLessons(id)}catch(e){msg(e.message,'error')}};
window.deleteLesson=async(lectureId,courseId)=>{if(!confirm('Remove this lesson? Students will no longer be able to attend it.'))return;try{const d=await api(`/lecturer/lectures/${lectureId}`,{method:'DELETE'});msg(d.message,'success');loadLecturerLessons(courseId)}catch(e){msg(e.message,'error')}};
async function loadLecturerAvailable(){const d=await api('/lecturer/available-courses');$('lecturer-available-courses').innerHTML=d.data.length?d.data.map(c=>`<div class="course-card"><h3>${esc(c.code)} — ${esc(c.name)}</h3><button class="btn primary" onclick="chooseCourse(${c.id})">Choose This Course</button></div>`).join(''):'<p class="muted">No unassigned course units are available.</p>'}
$('refresh-available-courses').onclick=loadLecturerAvailable;window.chooseCourse=async id=>{try{const d=await api('/lecturer/choose-course/'+id,{method:'POST'});msg(d.message,'success');loadLecturerCourses()}catch(e){msg(e.message,'error')}};
window.viewCourseStudents=async id=>{try{const d=await api(`/courses/lecturer/${id}/students`);$(`students-${id}`).innerHTML=d.data.length?`<div class="mini-actions">${d.data.map(s=>`<span class="muted">${esc(s.registrationNumber)} — ${esc(s.fullName)}</span>`).join('<br>')}</div>`:'<p class="muted">No students enrolled.</p>'}catch(e){msg(e.message,'error')}};
window.openCourseAttendance=id=>{showView('take-attendance');setTimeout(()=>{$('attendance-course').value=id;loadLiveAttendance()},0)};
async function prepareTakeAttendance(){const d=await api('/courses/lecturer');lecturerCourses=d.data;$('attendance-course').innerHTML='<option value="">Select course</option>'+d.data.map(c=>`<option value="${c.id}">${esc(c.code)} — ${esc(c.name)}</option>`).join('');$('take-attendance-area').innerHTML='<div class="card empty">Select a course and monitor attendance while the lecture is in progress.</div>'}
async function loadLiveAttendance(){const cid=$('attendance-course').value;if(!cid)return msg('Select a course first.','error');try{const d=await api('/attendance/lecturer/live?courseId='+encodeURIComponent(cid));const rows=d.data;const grouped={};(d.lectures||[]).forEach(l=>{grouped[l.id]={lecture:l,rows:[]}});rows.forEach(r=>{const k=r.lectureId||'none';(grouped[k] ||= {lecture:r.lecture,rows:[]}).rows.push(r)});const groups=Object.values(grouped);$('take-attendance-area').innerHTML=groups.length?groups.map(g=>`<div class="card"><h3>${g.lecture?`Every ${esc(g.lecture.dayOfWeek)} · ${esc(g.lecture.startTime)}-${esc(g.lecture.endTime)}`:'Attendance'}</h3><div id="lecture-pin-display-${g.lecture?.id}" class="message info">Generating current PIN…</div><p class="muted">Students who have joined: ${g.rows.length}</p><div class="table-scroll"><table><thead><tr><th>Student</th><th>Registration No.</th><th>Joined At</th><th>Status</th></tr></thead><tbody>${g.rows.map(r=>`<tr><td>${esc(r.student?.fullName||'')}</td><td>${esc(r.student?.registrationNumber||'')}</td><td>${esc(new Date(r.checkInTime).toLocaleTimeString())}</td><td class="status ${r.status}">${esc(r.status)}</td></tr>`).join('')}</tbody></table></div></div>`).join(''):'<div class="card empty">No lecture for this course is currently in progress.</div>';groups.forEach(g=>{if(g.lecture?.id)loadLecturePin(g.lecture.id)})}catch(e){msg(e.message,'error')}}
async function loadLecturePin(lectureId){try{const d=await api(`/attendance/lecturer/lectures/${lectureId}/pin`);const el=$(`lecture-pin-display-${lectureId}`);if(!el)return;const refreshIn=Math.max(0,new Date(d.data.expiresAt).getTime()-Date.now());el.innerHTML=`<b>Current attendance PIN: ${esc(d.data.pin)}</b><br><small>Changes in ${Math.ceil(refreshIn/1000)} seconds.</small>`;setTimeout(()=>{if($(`lecture-pin-display-${lectureId}`))loadLecturePin(lectureId)},refreshIn+100)}catch(e){const el=$(`lecture-pin-display-${lectureId}`);if(el){el.textContent=e.message;el.className='message error'}}}
$('load-attendance').onclick=loadLiveAttendance;$('refresh-live-attendance').onclick=loadLiveAttendance;
async function loadHistory(){const d=await api('/courses/lecturer');lecturerCourses=d.data;$('history-course').innerHTML='<option value="">All courses</option>'+d.data.map(c=>`<option value="${c.id}">${esc(c.code)} — ${esc(c.name)}</option>`).join('');refreshHistory()}$('filter-history').onclick=refreshHistory;async function refreshHistory(){const p=new URLSearchParams();if($('history-course').value)p.set('courseId',$('history-course').value);if($('history-date').value)p.set('date',$('history-date').value);if($('history-status').value)p.set('status',$('history-status').value);const d=await api('/attendance/lecturer/history?'+p);$('history-body').innerHTML=d.data.length?d.data.map(r=>`<tr><td>${esc(r.date)}</td><td>${esc(r.student?.fullName||'')}</td><td>${esc(r.course?.code||'')}</td><td class="status ${r.status}">${r.status}</td></tr>`).join(''):'<tr><td colspan="4">No matching records.</td></tr>'}
async function loadReports(){const d=await api('/attendance/lecturer/reports');$('reports-list').innerHTML=d.data.length?d.data.map(r=>`<div class="course-card"><h3>${esc(r.courseCode)} — ${esc(r.courseName)}</h3><p>Attended: ${r.attended} · Absent: ${r.absent} · Late: ${r.late}</p><b>Attendance: ${r.attendancePercentage}%</b></div>`).join(''):'<div class="card empty">No attendance data yet.</div>'}
function renderProfile(id){const u=user();$(id).innerHTML=`<h3>${esc(u.fullName)}</h3><p class="muted">${u.role==='lecturer'?'Lecturer ID':u.role==='student'?'Registration Number':'Role'}: ${esc(u.lecturerId||u.registrationNumber||u.role)}</p><p class="muted">Email: ${esc(u.email)}</p><button class="btn outline" onclick="showPage('forgot')">Reset Password</button>`}

const DAYS_OF_WEEK=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
async function loadAdminPrograms(){const [p,l]=await Promise.all([api('/admin/programs'),api('/admin/users?role=lecturer')]);$('admin-programs-list').innerHTML=p.data.length?p.data.map(prog=>`<div class="course-card"><h3>${esc(prog.code)} — ${esc(prog.name)}</h3><div class="controls"><button class="btn outline" id="edit-prog-toggle-${prog.id}" onclick="toggleEditProgram(${prog.id})">Edit</button><button class="btn danger" onclick="deleteProgram(${prog.id},'${esc(prog.code)}')">Delete Program</button></div><div id="edit-prog-${prog.id}" class="controls hidden" style="margin-top:10px"><input id="prog-name-${prog.id}" value="${esc(prog.name)}" placeholder="Program name"><label class="inline-check"><input type="checkbox" id="prog-active-${prog.id}" ${prog.isActive?'checked':''}> Active</label><button class="btn secondary" onclick="saveEditProgram(${prog.id})">Save Changes</button></div><div class="controls" style="margin-top:10px"><label class="muted" style="grid-column:1/-1">Add a course unit to this program</label><input id="course-code-${prog.id}" placeholder="Course code"><input id="course-name-${prog.id}" placeholder="Course name"><button class="btn secondary" onclick="addCourseToProgram(${prog.id})">Add Course Unit</button></div><h4 style="margin-top:12px">Course units</h4><div id="program-courses-${prog.id}" class="grid"></div></div>`).join(''):'<div class="card empty">No programs have been created yet.</div>';p.data.forEach(prog=>renderProgramCourses(prog,l.data))}
function renderProgramCourses(prog,lecturers){$(`program-courses-${prog.id}`).innerHTML=(prog.courses||[]).length?prog.courses.map(x=>`<div class="course-card"><h3>${esc(x.code)} — ${esc(x.name)}</h3><p class="muted">Lecturer: ${esc(x.lecturer?.fullName||'Not selected')}</p><div class="controls"><select id="assign-${x.id}"><option value="">Select lecturer</option>${lecturers.map(u=>`<option value="${u.id}" ${x.lecturerId===u.id?'selected':''}>${esc(u.fullName)} (${esc(u.lecturerId||'')})</option>`).join('')}</select><button class="btn primary" onclick="assignCourse(${x.id})">Assign</button><button class="btn outline" onclick="unassignCourse(${x.id})">Make Available</button><button class="btn outline" id="edit-toggle-${x.id}" onclick="toggleEditCourse(${x.id})">Edit</button><button class="btn danger" onclick="deleteCourse(${x.id},'${esc(x.code)}')">Delete</button></div><div id="edit-${x.id}" class="controls hidden" style="margin-top:10px"><input id="name-${x.id}" value="${esc(x.name)}" placeholder="Course name"><label class="inline-check"><input type="checkbox" id="active-${x.id}" ${x.isActive?'checked':''}> Active</label><button class="btn secondary" onclick="saveEditCourse(${x.id})">Save Changes</button></div></div>`).join(''):'<div class="card empty">No course units in this program yet.</div>'}
window.toggleEditProgram=id=>{$(`edit-prog-${id}`).classList.toggle('hidden')};
window.saveEditProgram=async id=>{try{const d=await api(`/admin/programs/${id}`,{method:'PUT',body:JSON.stringify({name:$(`prog-name-${id}`).value.trim(),isActive:$(`prog-active-${id}`).checked})});msg(d.message,'success');loadAdminPrograms()}catch(e){msg(e.message,'error')}};
window.deleteProgram=async(id,code)=>{if(!confirm(`Delete program ${code}? This also removes its course units, lessons, enrollments and attendance records.`))return;try{const d=await api(`/admin/programs/${id}`,{method:'DELETE'});msg(d.message,'success');loadAdminPrograms()}catch(e){msg(e.message,'error')}};
window.addCourseToProgram=async progId=>{const code=$(`course-code-${progId}`).value.trim(),name=$(`course-name-${progId}`).value.trim();if(!code||!name)return msg('Enter a course code and name.','error');try{const d=await api(`/admin/programs/${progId}/courses`,{method:'POST',body:JSON.stringify({code,name})});msg(d.message,'success');$(`course-code-${progId}`).value='';$(`course-name-${progId}`).value='';loadAdminPrograms()}catch(e){msg(e.message,'error')}};
window.toggleEditCourse=id=>{$(`edit-${id}`).classList.toggle('hidden')};
window.saveEditCourse=async id=>{try{const d=await api(`/admin/courses/${id}`,{method:'PUT',body:JSON.stringify({name:$(`name-${id}`).value.trim(),isActive:$(`active-${id}`).checked})});msg(d.message,'success');loadAdminPrograms()}catch(e){msg(e.message,'error')}};
window.deleteCourse=async(id,code)=>{if(!confirm(`Delete course unit ${code}? This also removes its lessons, enrollments and attendance records.`))return;try{const d=await api(`/admin/courses/${id}`,{method:'DELETE'});msg(d.message,'success');loadAdminPrograms()}catch(e){msg(e.message,'error')}};
window.assignCourse=async id=>{const lecturerId=$(`assign-${id}`).value;if(!lecturerId)return msg('Select a lecturer first.','error');try{const d=await api(`/admin/courses/${id}/assign`,{method:'POST',body:JSON.stringify({lecturerId:Number(lecturerId)})});msg(d.message,'success');loadAdminPrograms()}catch(e){msg(e.message,'error')}};window.unassignCourse=async id=>{try{const d=await api(`/admin/courses/${id}/unassign`,{method:'POST'});msg(d.message,'success');loadAdminPrograms()}catch(e){msg(e.message,'error')}};
$('admin-program-form').onsubmit=async e=>{e.preventDefault();try{const d=await api('/admin/programs',{method:'POST',body:JSON.stringify({code:$('admin-program-code').value.trim(),name:$('admin-program-name').value.trim()})});msg(d.message,'success');$('admin-program-form').reset();loadAdminPrograms()}catch(e){msg(e.message,'error')}};
async function loadAdminUsers(){const q=$('admin-user-role').value;const d=await api('/admin/users'+(q?'?role='+q:''));$('admin-users-list').innerHTML=d.data.map(u=>`<div class="course-card"><h3>${esc(u.fullName)}</h3><p>${esc(u.email)}</p><p class="muted">Role: ${esc(u.role)} · ${esc(u.registrationNumber||u.lecturerId||'')}</p></div>`).join('')||'<div class="card empty">No users found.</div>'}$('load-admin-users').onclick=loadAdminUsers;
async function loadAdminStudentAttendance(){const p=new URLSearchParams();if($('admin-student-date').value)p.set('date',$('admin-student-date').value);if($('admin-student-status').value)p.set('status',$('admin-student-status').value);const d=await api('/admin/attendance/students?'+p);$('admin-student-attendance-body').innerHTML=d.data.map(r=>`<tr><td>${esc(r.date)}</td><td>${esc(r.student?.fullName||'')}</td><td>${esc(r.course?.code||'')}</td><td><select id="st-${r.id}"><option ${r.status==='Present'?'selected':''}>Present</option><option ${r.status==='Absent'?'selected':''}>Absent</option><option ${r.status==='Late'?'selected':''}>Late</option></select></td><td><button class="btn outline" onclick="updateStudentAttendance(${r.id})">Save</button></td></tr>`).join('')||'<tr><td colspan="5">No records found.</td></tr>'}
$('load-admin-student-attendance').onclick=loadAdminStudentAttendance;window.updateStudentAttendance=async id=>{try{const d=await api('/admin/attendance/students/'+id,{method:'PUT',body:JSON.stringify({status:$(`st-${id}`).value})});msg(d.message,'success')}catch(e){msg(e.message,'error')}};
async function loadAdminLecturerAttendance(){const lecturers=await api('/admin/users?role=lecturer');$('admin-lecturer-select').innerHTML='<option value="">Select lecturer</option>'+lecturers.data.map(u=>`<option value="${u.id}">${esc(u.fullName)} (${esc(u.lecturerId||'')})</option>`).join('');const p=$('filter-lecturer-date').value?'?date='+encodeURIComponent($('filter-lecturer-date').value):'';const d=await api('/admin/attendance/lecturers'+p);$('admin-lecturer-attendance-body').innerHTML=d.data.map(r=>`<tr><td>${esc(r.date)}</td><td>${esc(r.lecturer?.fullName||'')}</td><td>${esc(r.lecturer?.lecturerId||'')}</td><td class="status ${r.status}">${r.status}</td></tr>`).join('')||'<tr><td colspan="4">No lecturer attendance records.</td></tr>'}
$('save-admin-lecturer-attendance').onclick=async()=>{try{if(!$('admin-lecturer-select').value||!$('admin-lecturer-date').value)return msg('Select lecturer and date.','error');const d=await api('/admin/attendance/lecturers',{method:'POST',body:JSON.stringify({lecturerId:Number($('admin-lecturer-select').value),date:$('admin-lecturer-date').value,status:$('admin-lecturer-status').value})});msg(d.message,'success');loadAdminLecturerAttendance()}catch(e){msg(e.message,'error')}};$('load-admin-lecturer-attendance').onclick=loadAdminLecturerAttendance;
// Admin can print the currently loaded attendance list. Only the target table is shown
// while printing; everything else (nav, filters, other alerts) is hidden via print CSS.
function printAttendanceList(cardId){document.body.classList.add('printing');$(cardId).classList.add('print-target');window.print()}
window.addEventListener('afterprint',()=>{document.body.classList.remove('printing');document.querySelectorAll('.print-target').forEach(x=>x.classList.remove('print-target'))});
$('print-admin-student-attendance').onclick=()=>printAttendanceList('admin-student-attendance-printarea');
$('print-admin-lecturer-attendance').onclick=()=>printAttendanceList('admin-lecturer-attendance-printarea');
function logout(){Object.keys(MESSAGE_TIMERS).forEach(k=>{if(MESSAGE_TIMERS[k])clearTimeout(MESSAGE_TIMERS[k])});localStorage.removeItem('campustrack_token');localStorage.removeItem('campustrack_user');showPage('login')}$('logout-btn').onclick=logout;
window.addEventListener('DOMContentLoaded',()=>{if(localStorage.getItem('campustrack_token'))openApp();else showPage('login')});
